### ISSUE TITLE
Still pushing as mthomann-lilly

### ISSUE THREAD

**Issue by mitchell-thomann** [mitchell-thomann/sfwR#4]
@wlandau: I believe that I updated my git settings properly via the shell (and confirmed with git config --global --list), but I'm still pushing via mthomann-lilly, is there anything obvious that I may be missing?

**Comment by wlandau** [comment]
That's a great thing to check, Mitch. As Jeff informed me a while back, the most important thing is that you used `git config` to define a non-default username. With no username at all, public commit history could show revealing ID numbers, and nobody likes to undo commits. 

Changing usernames can be tricky, so I tested it out just now to make sure I could still do it. From looking at [this commit log](https://github.com/wlandau-test/ooo/commits/master), I think the code below successfully changed the user from `wlandau-test` in https://github.com/wlandau-test/ooo/commit/ba79f29ff2ef92a14983d4ff90802ca5624ee234 to `wlandau` in https://github.com/wlandau-test/ooo/commit/2d7d4392563f4ca2f08a4a5226bf558eb8f80a82.

```
$ git config --global user.name "wlandau"
$ git config --global user.email "will.landau@gmail.com"
```

After that, running `git config --list` from outside [that repo](https://github.com/wlandau-test/ooo) looked like this.

```
user.email=will.landau@gmail.com
user.name=wlandau
push.default=simple
```

If my working directory is *inside* the repo, the information is slightly different.

```
$ git config --list
user.email=will.landau@gmail.com
user.name=wlandau
push.default=simple
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=git@github.com:wlandau-test/ooo
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
```

If your `user.name` and `user.email` for the repo disagree with your global settings, you may have to a `git config` inside the repo without the `--global` flag (just a guess).

**Comment by mitchell-thomann** [comment]
Thank you Will, that was a simple fix.

**Comment by mitchell-thomann** [comment]
@wlandau - running into a very odd problem similar to above.  I created a new repo using `mitchell-thomann` account.  The git global and local settings indicate that it is linked to this account (checked using git config and git config --global).  However when I push I received this error:

Mitchells-MacBook-Pro:doseCombR mthomann86$ git push -u origin master
remote: Permission to mitchell-thomann/doseCombR.git denied to mthomann-lilly.
fatal: unable to access 'https://github.com/mitchell-thomann/doseCombR.git/': The requested URL returnederror: 403

I fussed with this for quite some time, but via exploration I found that if I added `mthomann-lilly` as a collaborator then I was able to push to the repo, but it is pushing as `mitchell-thomann`.  I'm guessing there is some holdover information somewhere that is causing this weird issue, but I'm perplexed.  Do you have any thoughts?

**Comment by wlandau** [comment]
Could it be that you are trying to push to doseCombR (mentioned in your comment above) instead of sfwR?

Otherwise, I am not sure. I am travelling right now, and I cannot easily check on a computer this week, but I did find different ideas just from searching the 403 error code. For example, you may need to edit the URL field of the .git/config file.

**Comment by mitchell-thomann** [comment]
It is in doseCombR but it is odd that there is still some link between the two accounts.  No rush on this at all, I'm still able to work, but I appreciate your input if you have ideas.  

Enjoy your holiday!
